<a href="https://colab.research.google.com/github/ya3101/PRACTICAS-COMPUTACION/blob/main/Copia_de_Examen_ii.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install --target=$nb_path nacal
from nacal import *

1. Para la siguiente matriz $$\left[ \begin{array}{cccc}3&-2&2&1\\1&-1&-1&-3\\2&1&2&4\\4&-4&1&2\\ \end{array} \right]$$ lleva a cabo el algoritmo de eliminación paso a paso.

Escribe en una celda separada cada operacion elemental.

In [3]:
import numpy as np

# Definir la matriz original
A = np.array([
    [3, -2, 2, 1],
    [1, -1, -1, -3],
    [2, 1, 2, 4],
    [4, -4, 1, 2]
], dtype=float)  # Es importante definir la matriz con tipo de dato 'float'

print("Matriz original:")
print(A)

# Paso 1: Convertir el elemento a_{21} en cero utilizando la fila 1
A[1] = A[1] - (A[1,0]/A[0,0]) * A[0]

print("\nPaso 1:")
print(A)

# Paso 2: Convertir el elemento a_{31} en cero utilizando la fila 1
A[2] = A[2] - (A[2,0]/A[0,0]) * A[0]

print("\nPaso 2:")
print(A)

# Paso 3: Convertir el elemento a_{41} en cero utilizando la fila 1
A[3] = A[3] - (A[3,0]/A[0,0]) * A[0]

print("\nPaso 3:")
print(A)

# Paso 4: Convertir el elemento a_{32} en cero utilizando la fila 2
A[2] = A[2] - (A[2,1]/A[1,1]) * A[1]

print("\nPaso 4:")
print(A)

# Paso 5: Convertir el elemento a_{42} en cero utilizando la fila 2
A[3] = A[3] - (A[3,1]/A[1,1]) * A[1]

print("\nPaso 5:")
print(A)

# Paso 6: Convertir el elemento a_{43} en cero utilizando la fila 3
A[3] = A[3] - (A[3,2]/A[2,2]) * A[2]

print("\nPaso 6:")
print(A)


Matriz original:
[[ 3. -2.  2.  1.]
 [ 1. -1. -1. -3.]
 [ 2.  1.  2.  4.]
 [ 4. -4.  1.  2.]]

Paso 1:
[[ 3.         -2.          2.          1.        ]
 [ 0.         -0.33333333 -1.66666667 -3.33333333]
 [ 2.          1.          2.          4.        ]
 [ 4.         -4.          1.          2.        ]]

Paso 2:
[[ 3.         -2.          2.          1.        ]
 [ 0.         -0.33333333 -1.66666667 -3.33333333]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 4.         -4.          1.          2.        ]]

Paso 3:
[[ 3.         -2.          2.          1.        ]
 [ 0.         -0.33333333 -1.66666667 -3.33333333]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 0.         -1.33333333 -1.66666667  0.66666667]]

Paso 4:
[[  3.          -2.           2.           1.        ]
 [  0.          -0.33333333  -1.66666667  -3.33333333]
 [  0.           0.         -11.         -20.        ]
 [  0.          -1.33333333  -1.66666667   0.66666667]]

Paso 5:
[[  3.          -2.      

2. Escriba las siguientes matrices elementales de orden 4.


(a) I τ
[(−7)1+3]

(b) I τ
[(1)1+4]

(c) I τ
[(3)2+1]

(d) I τ
[(−10)3]

In [4]:
import numpy as np

# Matriz identidad de orden 4
I = np.eye(4)

# Matriz elemental (a)
a = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [-7, 0, 1, 0],
    [0, 0, 0, 1]
])

# Matriz elemental (b)
b = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [1, 0, 0, 1]
])

# Matriz elemental (c)
c = np.array([
    [1, 0, 0, 0],
    [3, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

# Matriz elemental (d)
d = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, -10, 0],
    [0, 0, 0, 1]
])

# Mostrar las matrices elementales
print("Matriz elemental (a):")
print(a)

print("\nMatriz elemental (b):")
print(b)

print("\nMatriz elemental (c):")
print(c)

Matriz elemental (a):
[[ 1  0  0  0]
 [ 0  1  0  0]
 [-7  0  1  0]
 [ 0  0  0  1]]

Matriz elemental (b):
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 1]]

Matriz elemental (c):
[[1 0 0 0]
 [3 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


3. Sea la matriz A = $\left[ \begin{array}{cccc}1&1&1&1\\0&1&1&1\\1&2&3&4\\4&-4&1&2\\ \end{array} \right]$
, exprese las siguientes transformaciones elementales de

A como productos de A por matrices elementales y escriba el resultado:

(a) Multiplicar la primera columna por 3. (b) Restar la primera columna de la segunda.

In [5]:
import numpy as np

# Definir la matriz original A
A = np.array([
    [1, 1, 1, 1],
    [0, 1, 1, 1],
    [1, 2, 3, 4],
    [4, -4, 1, 2]
])

print("Matriz original:")
print(A)

# (a) Definir la matriz elemental para multiplicar la primera columna por 3
E1 = np.array([
    [3, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

# Multiplicar A por E1 para multiplicar la primera columna por 3
A_por_E1 = np.dot(A, E1)

print("\nResultado de multiplicar la primera columna por 3:")
print(A_por_E1)

# (b) Definir la matriz elemental para restar la primera columna de la segunda
E2 = np.array([
    [1, 0, 0, 0],
    [-1, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

# Multiplicar A por E2 para restar la primera columna de la segunda
A_por_E2 = np.dot(A, E2)

print("\nResultado de restar la primera columna de la segunda:")
print(A_por_E2)


Matriz original:
[[ 1  1  1  1]
 [ 0  1  1  1]
 [ 1  2  3  4]
 [ 4 -4  1  2]]

Resultado de multiplicar la primera columna por 3:
[[ 3  1  1  1]
 [ 0  1  1  1]
 [ 3  2  3  4]
 [12 -4  1  2]]

Resultado de restar la primera columna de la segunda:
[[ 0  1  1  1]
 [-1  1  1  1]
 [-1  2  3  4]
 [ 8 -4  1  2]]


4. Realiza el algoritmo de eliminación de Gauss-Jordan para la matriz del ejercicio 1, es decir continua las modificaciones de la matriz mediante operaciones elementales.
Por cada paso del algoritmo escribe la celda de código correspondiente.

In [6]:
import numpy as np

# Definir la matriz original
A = np.array([
    [3, -2, 2, 1],
    [1, -1, -1, -3],
    [2, 1, 2, 4],
    [4, -4, 1, 2]
], dtype=float)

print("Matriz original:")
print(A)

# Paso 1: Convertir el elemento a_{21} en cero utilizando la fila 1
A[1] = A[1] - (A[1,0]/A[0,0]) * A[0]

print("\nPaso 1:")
print(A)

# Paso 2: Convertir el elemento a_{31} en cero utilizando la fila 1
A[2] = A[2] - (A[2,0]/A[0,0]) * A[0]

print("\nPaso 2:")
print(A)

# Paso 3: Convertir el elemento a_{41} en cero utilizando la fila 1
A[3] = A[3] - (A[3,0]/A[0,0]) * A[0]

print("\nPaso 3:")
print(A)

# Paso 4: Convertir el elemento a_{32} en cero utilizando la fila 2
A[2] = A[2] - (A[2,1]/A[1,1]) * A[1]

print("\nPaso 4:")
print(A)

# Paso 5: Convertir el elemento a_{42} en cero utilizando la fila 2
A[3] = A[3] - (A[3,1]/A[1,1]) * A[1]

print("\nPaso 5:")
print(A)

# Paso 6: Convertir el elemento a_{43} en cero utilizando la fila 3
A[3] = A[3] - (A[3,2]/A[2,2]) * A[2]

print("\nPaso 6:")
print(A)

# Paso 7: Convertir el elemento a_{32} en cero utilizando la fila 3
A[1] = A[1] - (A[1,2]/A[2,2]) * A[2]

print("\nPaso 7:")
print(A)

# Paso 8: Convertir el elemento a_{31} en cero utilizando la fila 3
A[0] = A[0] - (A[0,2]/A[2,2]) * A[2]

print("\nPaso 8:")
print(A)

# Paso 9: Convertir el elemento a_{21} en cero utilizando la fila 2
A[0] = A[0] - (A[0,1]/A[1,1]) * A[1]

print("\nPaso 9:")
print(A)

# Paso 10: Convertir el elemento a_{43} en uno utilizando la fila 4
A[3] = A[3] / A[3,3]

print("\nPaso 10:")
print(A)

# Paso 11: Convertir el elemento a_{33} en uno utilizando la fila 3
A[2] = A[2] / A[2,2]

print("\nPaso 11:")
print(A)

# Paso 12: Convertir el elemento a_{23} en cero utilizando la fila 2
A[1] = A[1] - A[1,2] * A[2]

print("\nPaso 12:")
print(A)

# Paso 13: Convertir el elemento a_{13} en cero utilizando la fila 1
A[0] = A[0] - A[0,2] * A[2]

print("\nPaso 13:")
print(A)


Matriz original:
[[ 3. -2.  2.  1.]
 [ 1. -1. -1. -3.]
 [ 2.  1.  2.  4.]
 [ 4. -4.  1.  2.]]

Paso 1:
[[ 3.         -2.          2.          1.        ]
 [ 0.         -0.33333333 -1.66666667 -3.33333333]
 [ 2.          1.          2.          4.        ]
 [ 4.         -4.          1.          2.        ]]

Paso 2:
[[ 3.         -2.          2.          1.        ]
 [ 0.         -0.33333333 -1.66666667 -3.33333333]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 4.         -4.          1.          2.        ]]

Paso 3:
[[ 3.         -2.          2.          1.        ]
 [ 0.         -0.33333333 -1.66666667 -3.33333333]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 0.         -1.33333333 -1.66666667  0.66666667]]

Paso 4:
[[  3.          -2.           2.           1.        ]
 [  0.          -0.33333333  -1.66666667  -3.33333333]
 [  0.           0.         -11.         -20.        ]
 [  0.          -1.33333333  -1.66666667   0.66666667]]

Paso 5:
[[  3.          -2.      

5. Compara tus resultados del ejercicio 1 con el metodo Elim()

 6. Compara tus resultados del ejercicio 4 con el metodo ElimGJ()

7. Encuentra la inversa de la matriz del ejercicio 1.

In [7]:
import numpy as np

# Definir la matriz original
A = np.array([
    [3, -2, 2, 1],
    [1, -1, -1, -3],
    [2, 1, 2, 4],
    [4, -4, 1, 2]
], dtype=float)

print("Matriz original:")
print(A)

# Calcular la inversa de la matriz
A_inversa = np.linalg.inv(A)

print("\nInversa de la matriz:")
print(A_inversa)


Matriz original:
[[ 3. -2.  2.  1.]
 [ 1. -1. -1. -3.]
 [ 2.  1.  2.  4.]
 [ 4. -4.  1.  2.]]

Inversa de la matriz:
[[-0.16666667  0.5         0.38888889  0.05555556]
 [-0.11111111  0.33333333  0.37037037 -0.18518519]
 [ 0.77777778 -0.33333333 -0.25925926 -0.37037037]
 [-0.27777778 -0.16666667  0.09259259  0.2037037 ]]


8. Resuelva el siguiente sistema de ecuaciones:

$$ \begin{array}{ccc}5x&+7y&-z&=6\\2x&+10y&-2z&=4\\x&+y&+z&=0\\ \end{array} $$

In [8]:
import numpy as np

# Coeficientes de las variables en las ecuaciones
coefficients = np.array([
    [5, 7, -1],   # Coeficientes de x, y, z en la primera ecuación
    [2, 10, -2],  # Coeficientes de x, y, z en la segunda ecuación
    [1, 1, 1],    # Coeficientes de x, y, z en la tercera ecuación
])

# Lado derecho de las ecuaciones
constants = np.array([6, 4, 0])

# Resolver el sistema de ecuaciones
solution = np.linalg.solve(coefficients, constants)

print("Solución del sistema:")
print("x =", solution[0])
print("y =", solution[1])
print("z =", solution[2])

Solución del sistema:
x = 1.0000000000000002
y = -1.2335811384723962e-16
z = -1.0000000000000002
