<a href="https://colab.research.google.com/github/ya3101/PRACTICAS-COMPUTACION/blob/main/Copia_de_Examen1AL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Algebra Lineal

### 1er examen parcial

EN este notebook deberás realizar cada uno de los ejercicios utilizando Python dentro de los bloques de código, si alguna salida requiere la visualización mediante Latex escribe el bloque correspondiente.

1. Genere los vectores $a$ y $ {b}$:

-   el vector ${a}$ está formado por la lista de números: 1, 4, 9, 2, -5, π
-   el vector ${b}$ está formado por la lista de números: 1, 2, 1, 0, 0.01,  $\sqrt 2$
-   súmelos

In [6]:
import math

# Definir las listas de números para los vectores a y b
lista_a = [1, 4, 9, 2, -5, math.pi]
lista_b = [1, 2, 1, 0, 0.01, math.sqrt(2)]

# Imprimir los vectores a y b
print("Vector a:", lista_a)
print("Vector b:", lista_b)

# Sumar los elementos correspondientes de los vectores a y b
resultado = [x + y for x, y in zip(lista_a, lista_b)]

# Mostrar el resultado
print("El resultado de la suma de los vectores a y b es:", resultado)


Vector a: [1, 4, 9, 2, -5, 3.141592653589793]
Vector b: [1, 2, 1, 0, 0.01, 1.4142135623730951]
El resultado de la suma de los vectores a y b es: [2, 6, 10, 2, -4.99, 4.555806215962888]


2. Proporcione ejemplos de matrices 3 por 3 no nulas de los siguientes
tipos de matrices:

-   Una matriz diagonal



-   Una matriz simétrica



In [8]:
import numpy as np

# Matriz diagonal
matriz_diagonal = np.array([
    [2, 0, 0],
    [0, 3, 0],
    [0, 0, 5]
])

print("Matriz Diagonal:")
print(matriz_diagonal)

# Matriz simétrica
matriz_simetrica = np.array([
    [1, 2, 3],
    [2, 4, 5],
    [3, 5, 6]
])

print("\nMatriz Simétrica:")
print(matriz_simetrica)


Matriz Diagonal:
[[2 0 0]
 [0 3 0]
 [0 0 5]]

Matriz Simétrica:
[[1 2 3]
 [2 4 5]
 [3 5 6]]


3. Cree la matriz
$${A}=\begin{bmatrix}1&0&0&-1\\2&0&7&0\\-4&3&3&0\\0&3&4&1\\7&1&2&1\end{bmatrix}$$



In [12]:
import numpy as np

# Definir la matriz A
A = np.array([
    [1, 0, 0, -1],
    [2, 0, 7,  0],
    [-4, 3, 3, 0],
    [0, 3, 4,  1],
    [7, 1, 2,  1]
])

print("Matriz A:")
print(A)


Matriz A:
[[ 1  0  0 -1]
 [ 2  0  7  0]
 [-4  3  3  0]
 [ 0  3  4  1]
 [ 7  1  2  1]]


Calcule el siguiente vector: 3 veces la primera columna de $A$
mas la segunda columna de $A$ menos 2 veces la tercera columna
menos 3 veces la última columna de $A$



In [13]:
import numpy as np

# Definir la matriz A
A = np.array([
    [12, -4, 70, 3],
    [33, 10, 73, 4],
    [42, -100, 11, 5]
])

# Extraer las columnas de A
columna_1 = A[:, 0]  # Primera columna
columna_2 = A[:, 1]  # Segunda columna
columna_3 = A[:, 2]  # Tercera columna
columna_4 = A[:, 3]  # Cuarta columna

# Calcular el vector según la expresión dada
resultado = 3 * columna_1 + columna_2 - 2 * columna_3 - 3 * columna_4

print("El vector resultante es:", resultado)


El vector resultante es: [-117  -49  -11]


4. Matriz por vector (combinaciones lineales de las columnas de una matriz)

Considere los vectores ${x}=(1, 1, -2)$, ${y}=(1, -2, 1)$

y
${z}=(-2, 1, 1)$ y verifique que
$2{x}+2{y}+2{z}={0}$

que resultado da : $4x+4y+4z$

y que resultado da:  $-3x-3y-3z$

In [14]:
# Definir los vectores x, y, y z
x = [1, 1, -2]
y = [1, -2, 1]
z = [-2, 1, 1]

# Verificar 2x + 2y + 2z
resultado_1 = [2*a + 2*b + 2*c for a, b, c in zip(x, y, z)]
print("Resultado de 2x + 2y + 2z:", resultado_1)

# Verificar 4x + 4y + 4z
resultado_2 = [4*a + 4*b + 4*c for a, b, c in zip(x, y, z)]
print("Resultado de 4x + 4y + 4z:", resultado_2)

# Verificar -3x - 3y - 3z
resultado_3 = [-3*a - 3*b - 3*c for a, b, c in zip(x, y, z)]
print("Resultado de -3x - 3y - 3z:", resultado_3)


Resultado de 2x + 2y + 2z: [0, 0, 0]
Resultado de 4x + 4y + 4z: [0, 0, 0]
Resultado de -3x - 3y - 3z: [0, 0, 0]


5. Escribe una matriz C del mismo orden que A y verifica que
$$
({A}{C})^T={C}^T{A}^T
$$

In [15]:
import numpy as np

# Definir las matrices A y C
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

C = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])

# Multiplicar las matrices A y c
AC = np.dot(A, C)

# Calcular la transposición de AC
AC_transpuesta = np.transpose(AC)

# Calcular C^T y A^T
C_transpuesta = np.transpose(C)
A_transpuesta = np.transpose(A)

# Calcular C^T A^T
CT_AT = np.dot(C_transpuesta, A_transpuesta)

# Verificar la igualdad
son_iguales = np.array_equal(AC_transpuesta, CT_AT)

# Mostrar resultados
print("Matriz AC:")
print(AC)
print("\nTranspuesta de AC:")
print(AC_transpuesta)
print("\nC^T A^T:")
print(CT_AT)

if son_iguales:
    print("\nLa igualdad (AC)^T = C^T A^T se cumple.")
else:
    print("\nLa igualdad (AC)^T = C^T A^T no se cumple.")


Matriz AC:
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]

Transpuesta de AC:
[[ 90 216 342]
 [ 96 231 366]
 [102 246 390]]

C^T A^T:
[[ 90 216 342]
 [ 96 231 366]
 [102 246 390]]

La igualdad (AC)^T = C^T A^T se cumple.


6. Verifique que
$
{A}{I}={A}
$
y que
$
{I}{A}={A}
$

In [ ]:
import numpy as np

# Definir la matriz A
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Obtener el orden de la matriz A
orden = A.shape[0]

# Construir la matriz identidad del mismo orden que A
I = np.eye(orden)

# Verificar AI = A
AI = np.dot(A, I)
print("AI:")
print(AI)

# Verificar IA = A
IA = np.dot(I, A)
print("\nIA:")
print(IA)

# Verificar si AI = A y IA = A
condicion_AI = np.array_equal(AI, A)
condicion_IA = np.array_equal(IA, A)

# Mostrar resultados
if condicion_AI:
    print("\nLa igualdad AI = A se cumple.")
else:
    print("\nLa igualdad AI = A no se cumple.")

if condicion_IA:
    print("La igualdad IA = A se cumple.")
else:
    print("La igualdad IA = A no se cumple.")


7. Producto punto
Considere los vectores ${x}=(1, 1, -2)$, ${y}=(1, -2, 1)$
calcula el producto punto

In [ ]:
# Definir los vectores x y y
x = [1, 1, -2]
y = [1, -2, 1]

# Calcular el producto punto
producto_punto = sum(x_i * y_i for x_i, y_i in zip(x, y))

# Mostrar el resultado
print("El producto punto entre x y y es:", producto_punto)
