<a href="https://colab.research.google.com/github/ya3101/PRACTICAS-COMPUTACION/blob/main/Copia_de_Examen1AL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Algebra Lineal

### 1er examen parcial

EN este notebook deberás realizar cada uno de los ejercicios utilizando Python dentro de los bloques de código, si alguna salida requiere la visualización mediante Latex escribe el bloque correspondiente.

1. Genere los vectores $a$ y $ {b}$:

-   el vector ${a}$ está formado por la lista de números: 1, 4, 9, 2, -5, π
-   el vector ${b}$ está formado por la lista de números: 1, 2, 1, 0, 0.01,  $\sqrt 2$
-   súmelos

In [6]:
import math

# Definir las listas de números para los vectores a y b
lista_a = [1, 4, 9, 2, -5, math.pi]
lista_b = [1, 2, 1, 0, 0.01, math.sqrt(2)]

# Imprimir los vectores a y b
print("Vector a:", lista_a)
print("Vector b:", lista_b)

# Sumar los elementos correspondientes de los vectores a y b
resultado = [x + y for x, y in zip(lista_a, lista_b)]

# Mostrar el resultado
print("El resultado de la suma de los vectores a y b es:", resultado)


Vector a: [1, 4, 9, 2, -5, 3.141592653589793]
Vector b: [1, 2, 1, 0, 0.01, 1.4142135623730951]
El resultado de la suma de los vectores a y b es: [2, 6, 10, 2, -4.99, 4.555806215962888]


2. Proporcione ejemplos de matrices 3 por 3 no nulas de los siguientes
tipos de matrices:

-   Una matriz diagonal



-   Una matriz simétrica



In [8]:
import numpy as np

# Matriz diagonal
matriz_diagonal = np.array([
    [2, 0, 0],
    [0, 3, 0],
    [0, 0, 5]
])

print("Matriz Diagonal:")
print(matriz_diagonal)

# Matriz simétrica
matriz_simetrica = np.array([
    [1, 2, 3],
    [2, 4, 5],
    [3, 5, 6]
])

print("\nMatriz Simétrica:")
print(matriz_simetrica)


Matriz Diagonal:
[[2 0 0]
 [0 3 0]
 [0 0 5]]

Matriz Simétrica:
[[1 2 3]
 [2 4 5]
 [3 5 6]]


3. Cree la matriz
$${A}=\begin{bmatrix}1&0&0&-1\\2&0&7&0\\-4&3&3&0\\0&3&4&1\\7&1&2&1\end{bmatrix}$$



In [12]:
import numpy as np

# Definir la matriz A
A = np.array([
    [1, 0, 0, -1],
    [2, 0, 7,  0],
    [-4, 3, 3, 0],
    [0, 3, 4,  1],
    [7, 1, 2,  1]
])

print("Matriz A:")
print(A)


Matriz A:
[[ 1  0  0 -1]
 [ 2  0  7  0]
 [-4  3  3  0]
 [ 0  3  4  1]
 [ 7  1  2  1]]


Calcule el siguiente vector: 3 veces la primera columna de $A$
mas la segunda columna de $A$ menos 2 veces la tercera columna
menos 3 veces la última columna de $A$



4. Matriz por vector (combinaciones lineales de las columnas de una matriz)

Considere los vectores ${x}=(1, 1, -2)$, ${y}=(1, -2, 1)$

y
${z}=(-2, 1, 1)$ y verifique que
$2{x}+2{y}+2{z}={0}$

que resultado da : $4x+4y+4z$

y que resultado da:  $-3x-3y-3z$

5. Escribe una matriz C del mismo orden que A y verifica que
$$
({A}{C})^T={C}^T{A}^T
$$

6. Verifique que
$
{A}{I}={A}
$
y que
$
{I}{A}={A}
$

7. Producto punto
Considere los vectores ${x}=(1, 1, -2)$, ${y}=(1, -2, 1)$
calcula el producto punto